import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Software Engineer',
    company: 'CoForge',
    logo: '/images/careers/CoForge.png',
    location: 'Hyderabad, TS IN',
    type: 'Full-time',
    start_date: '2020-07',
    end_date: '2021-10',
    industry: 'Software Applications',
    link: 'https://www.coforge.com/',
    responsibilities: [
      'Developed and optimized a cloud-based urban planning system using Java Spring Boot, reducing response times by 40%, enabling thousands of daily users to access real-time property and zoning data efficiently.',
      'Designed and delivered RESTful APIs for geospatial data retrieval, utilizing PostgreSQL and PostGIS to enhance accuracy and cut down query times by 35%, supporting large-scale city infrastructure planning.',
      'Engineered an interactive geospatial mapping interface with React and Mapbox, improving responsiveness by 50% and increasing user adoption by 25%, enabling better decision-making for urban planners.',
      'Enhanced geospatial visualization by integrating zoning overlays and real-time property insights, reducing manual analysis time by 40% and accelerating decision-making for urban planners.',
      'Fine-tuned and facilitated 45+ React components, including dynamic data visualizations with graphs and charts, enhancing stakeholder decision-making and improving data accessibility by 40%.',
      'Implemented a microservices architecture, improving system scalability and reliability, reducing downtime by 30%, and ensuring maintainability for future system expansions.',
      'Automated core development workflows with CI/CD pipelines, increasing deployment efficiency by 45%, reducing manual errors, and ensuring smooth feature rollouts.',
      'Launched a responsive React.js Application Tracker, improving real-time updates on development applications and enhancing UI scalability with reusable components.',
      'Built stateful systems and stateless REST APIs using Node.js, ensuring seamless data flow between frontend and backend while improving system resilience.',
      'Pioneered and implemented a scalable API integration framework connecting customer systems with real-time planning services, supporting legacy, GraphQL, and REST APIs, reducing development overhead and accelerating feature deployment by 40%.',
      'Authored comprehensive technical documentation and integration specifications, streamlining onboarding and reducing integration time by 30%.',
      'Contributed to sprint planning and backlog grooming, optimized feature prioritization to accelerate API delivery by 30%, ensured alignment with business objectives, and enhanced cross-team collaboration.',
    ],
  },
  {
    position: 'Software Engineer Intern',
    company: 'CoForge',
    logo: '/images/careers/CoForge.png',
    location: 'Hyderabad, TS 🇮🇳',
    type: 'Internship',
    start_date: '2020-06',
    end_date: '2019-07',
    industry: 'Software Applications',
    link: 'https://www.coforge.com/',
    responsibilities: [
      'Led a team of 5 interns in developing and delivering a web-based solution, ensuring timely completion and adherence to best coding practices.',
      'Owned key development tasks, proactively identifying and resolving technical challenges, improving system performance by 30%.',
      'Developed a centralized dashboard using React, Node.js, and PostgreSQL, enhancing system monitoring and improving operational efficiency by 40%. ',
      'Designed UI wireframes in Figma, improving user experience and reducing development rework by 30% through structured design implementation.',
      'Devised and integrated AI-powered chatbots for a major UK insurance portal, automating support and reducing response times by 70%.',
      'Leveraged reusable automation services for claims processing and policy management, reducing manual effort by 50% and enhancing scalability.',
      'Formulated proof-of-concept (POC) solutions that secured high-value project deals, contributing to a 30% increase in client acquisition through successful live demonstrations.',
      'Developed reusable automation scripts in Python, reducing manual testing efforts and accelerating deployment cycles by 45%.',
      'Participated in code review processes, ensuring maintainable code and achieving a 45% reduction in post-deployment issues.',
    ],
  },
];
